name: Flutter 自动打包

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: "3.10.6"

    - name: Build Android APK
      run: flutter build apk

    - name: Upload Android APK to GitHub Releases
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: ./build/app/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
